name: secrets
on: [push]
jobs:
    secret-scan:
        name: secret-scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: scan
              uses: edplato/trufflehog-actions-scan@v0.9i-beta
